### ISSUE TITLE
Improve usage documentation

### ISSUE THREAD

**Issue by brtastic** [cpanery/test-db#23]
Hello, 
first of all, thank you for this module. It helps me a lot with integration testing in my application.

While it is useful indeed, I found it pretty hard to get up and running. The documentation and examples are a bit lacking, and I found myself reading the internal code a lot to get the idea. The non-standard subroutine syntax did not help either. 

My use case is quite simple: clone a database, get a newly created database name, set up my system to use that new database, perform testing and clean it all up. Some problems I had while setting that up:
- how do I pass database type to `clone` method, other than via %ENV?
- should I specify a dbh, dsn or host/port/username/password? (tried it all in this order, the last one is correct)
- how do I get the newly created test database name? (I'm using Mojo::Pg, so I think I can't re-use the dbh from the object)

I managed to get the answers from code after all, but documentation and examples were not very helpful. My resulting code looks like this:
```
my $testdb = Test::DB->new;

$ENV{TESTDB_DATABASE} = 'postgres';
my $cloned = $testdb->clone(
	hostname => $config->{db}{host},
	hostport => $config->{db}{port},
	username => $config->{db}{username},
	password => $config->{db}{password},
	template => $config->{db}{database},
);

die 'database clone error' unless defined $cloned;

my $db = Mojo::Pg->new->dsn($cloned->dsn)
	->username($config->{db}{username})
	->password($config->{db}{password})
	->db;

try {
	... # test code
} finally {
	$db->disconnect;
	$cloned->destroy;
}
```

Would be nice to see a full working example that is not basic (like the one above) in the docs or the examples - all the examples are currently the same thing but with different database flavour.

**Comment by iamalnewkirk** [comment]
@brtastic Thanks so much for the helpful feedback! I just stumbled upon the fact the passing `database` to `create` or `clone` doesn't work, and you have to use `TESTDB_DATABASE`. I know what the problem is so I'll fix it shortly. I'll also flush out more thorough examples. Can I tag you for a review in the PR when it's ready?

**Comment by brtastic** [comment]
Thanks @iamalnewkirk, I'll be happy to review the changes once they're done

**Comment by iamalnewkirk** [comment]
To address this issue I will do the following:

- [Fix all key/value pair unpacking method signatures](https://github.com/cpanery/test-db/issues/25)
   (so that passing key/value pairs work as expected, no need to setup env vars)
- [Add support for returning DB URIs](https://github.com/cpanery/test-db/issues/24)
   (for easy integration with drivers that support URI strings, e.g. Mojo::Pg)

Additionally, I will push another PR which does the following:

- Add db-specific builder methods to the main module for convenience

```
use Test::DB;

my $tdb = Test::DB->new;
my $tdbo = $tdb->postgres(%options)->clone;
```

- Add how-it-works documentation in the main module

```
# creating, cloning, and destroying

(on create, clone)
# 1. establish a connection to the DB using some "initial" database
# 2. using the established connection to create the test/temporary database
# 3. establish a connection to the newly created test/temporary database
# 4. make the test database object immutable
(on destroy)
# 4. establish a connection to the DB using the "initial" database
# 5. using the established connection, drop the test/temporary database
```

- Add scenario-documentation (documentation of common scenarios) in the main module

```
use Test::DB;

# using DBI
my $tdb = Test::DB->new;
my $dbh = $tdb->sqlite(%options)->dbh;

# using DBIx::Class
my $tdb = Test::DB->new;
my $tdbo = $tdb->postgres(%options)->create;
my $schema = DBIx::Class::Schema->connect(
  dsn => $tdbo->dsn,
  username => $tdbo->username,
  password => $tdbo->password,
);

# using Mojo::mysql
my $tdb = Test::DB->new;
my $tdbo = $tdb->mysql(%options)->create;
my $mysql = Mojo::mysql->new($tdbo->uri);

# using Mojo::Pg
my $tdb = Test::DB->new;
my $tdbo = $tdb->postgres(%options)->create;
my $postgres = Mojo::Pg->new($tdbo->uri);

# using Mojo::Pg (with cloning)
my $tdb = Test::DB->new;
my $tdbo = $tdb->postgres(%options)->clone('template0');
my $postgres = Mojo::Pg->new($tdbo->uri);

# using Mojo::SQLite
my $tdb = Test::DB->new;
my $tdbo = $tdb->sqlite(%options)->create;
my $sqlite = Mojo::SQLite->new($tdbo->uri);
```

**Comment by brtastic** [comment]
@iamalnewkirk that looks very good, but I think an example in synopsis like mine (the try-finally one) could also be added for clarity. 

Test databases will just stick in the database until manually removed if the `->destroy` method is not called. Would be nice to let the reader know there's no DESTROY black magic or anything that will clean up automatically in case of an exception.

Or alternatively, there could exist a method that will clone, run a sub inside a try-catch and call `->destroy` on error (or after finishing). Seems to me that will be a frequent use case:

```
my $tdb = Test::DB->new;
$tdb->postgres(%options);
$tdb->test_this(sub {
    # this should be ran inside a try-catch after cloning successfully
    # upon error or when finished it should call destroy()
    # it can also function like other test methods, with the test message below:
}, 'database test ok');
```

**Comment by iamalnewkirk** [comment]
Will release the changes after this PR, https://github.com/cpanery/test-db/pull/28, passes its testing. I truly appreciate the suggestions. I want the documentation to be clear, but I also don't want to include situational implementation details. E.g. using try/catch isn't necessary to use this library.

**Comment by brtastic** [comment]
@iamalnewkirk thanks, appreciated. try/catch isn't required indeed, it's just my preference to be sure I clean up afterwards ;)

**Comment by iamalnewkirk** [comment]
@brtastic thanks for the insight and feedback, let me know if you have further questions. Version 0.07 has been released, Here's the updated documentation! https://github.com/cpanery/test-db#description
